# Generated by Django 6.0.1 on 2026-01-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
    ]
