# Generated by Django 6.0.1 on 2026-01-25 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_challenge_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='audio',
        ),
    ]
