# Generated by Django 6.0.1 on 2026-01-25 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='letter',
        ),
        migrations.AddField(
            model_name='challenge',
            name='word',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='challenges.word'),
            preserve_default=False,
        ),
    ]
