# Generated by Django 6.0.1 on 2026-01-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_challenge_letter_challenge_word'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
