# Generated by Django 6.0.1 on 2026-01-26 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_word_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='audio',
            field=models.URLField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
