# Generated by Django 6.0.1 on 2026-01-30 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_alter_word_audio'),
    ]

    operations = [
        migrations.CreateModel(
            name='YesNoQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_description', models.CharField(help_text="Description of the visual scene (e.g., 'Girl is jumping')", max_length=200)),
                ('question', models.CharField(help_text="The Yes/No question (e.g., 'Is she jumping?')", max_length=200)),
                ('answer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('visual_url', models.URLField(blank=True, help_text='Cloudinary URL for the visual image', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Yes/No Questions',
            },
        ),
    ]
