# Generated by Django 6.0.1 on 2026-01-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0007_yesnoquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='yesnoquestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='yesnoquestion',
            name='visual',
            field=models.FileField(blank=True, help_text='Upload image or short video clip (max 5MB, prefer .jpg/.png or .mp4)', null=True, upload_to='yesno_visuals/'),
        ),
        migrations.AlterField(
            model_name='yesnoquestion',
            name='visual_url',
            field=models.URLField(blank=True, editable=False, null=True),
        ),
    ]
