# Generated by Django 6.0.1 on 2026-01-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0008_yesnoquestion_updated_at_yesnoquestion_visual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yesnoquestion',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='yesnoquestion',
            name='visual',
        ),
        migrations.AddField(
            model_name='yesnoquestion',
            name='correct_answer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='', help_text='Correct answer', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yesnoquestion',
            name='question',
            field=models.CharField(help_text="The yes/no question, e.g. 'Is she jumping?'", max_length=200),
        ),
        migrations.AlterField(
            model_name='yesnoquestion',
            name='scene_description',
            field=models.CharField(help_text="Short description of the visual scene, e.g. 'Girl is jumping'", max_length=200),
        ),
        migrations.AlterField(
            model_name='yesnoquestion',
            name='visual_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for image or video (auto-filled after upload)', null=True),
        ),
    ]
