# Generated by Django 6.0.1 on 2026-01-31 01:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_remove_yesnoquestion_answer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='challenge_type',
            field=models.CharField(default='letter', max_length=20),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='yes_no_question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.yesnoquestion'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'challenge'), ('user', 'yes_no_question')},
        ),
    ]
