# Generated by Django 6.0.1 on 2026-01-31 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0010_userprogress_challenge_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprogress',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
    ]
