# Generated by Django 6.0.1 on 2026-01-31 22:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_alter_userprogress_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FunctionalPhrase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phrase', models.CharField(help_text="The exact phrase the child should say, e.g. 'I want water'", max_length=200)),
                ('visual_url', models.URLField(blank=True, help_text='Cloudinary URL for image or short video (auto-filled after upload)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Functional Phrases',
            },
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'challenge'), ('user', 'yes_no_question')},
        ),
        migrations.AddField(
            model_name='userprogress',
            name='functional_phrase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='challenges.functionalphrase'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('user', 'challenge'), ('user', 'functional_phrase'), ('user', 'yes_no_question')},
        ),
    ]
